### ISSUE TITLE
What happened to the .message chained method?

### ISSUE THREAD

**Issue by millisami** [bcardarella/valid_attribute#12]
Earlier, the following spec used to pass.

``` shell
it { should_not have_valid(:email).when('1wey', '1234@').message('is invalid') }
```

But since the upgraded version, its showing the error.

``` shell
NoMethodError:
       undefined method `message' for #<ValidAttribute::Matcher:0x00000102f119d8>
```

I really liked that method coz it gives me the way to test the custom message at the same time?
Is it deprecated or replaced with other method?
I couldn't find any in the README too.

**Comment by bcardarella** [comment]
`#message` was removed from the pre-1.0 release as it doesn't test anything functional.

In addition, if you are testing multiple values on a single attribute like this:

``` ruby
before { User.create(:email => 'taken@test.com') }
it { should_not have_valid(:email).with(nil, '', 'test', 'taken@test.com') }
```

`ValidAttribute` is testing at least three difference validators here: `presence`, `format` and `uniqueness` each with different messages.

**Comment by millisami** [comment]
Alright. Thanks for the explanation. Keep Up the great work!
