### ISSUE TITLE
Cannot get it to work with Minitest

### ISSUE THREAD

**Issue by grimen** [bcardarella/valid_attribute#17]
I'm following the example for using valid_attribute with minitest from the README like so:

``` ruby
describe "Validations" do
  subject { Factory.build(:product_tag) }

  it { subject.must have_valid(:x).when(0) }
end
```

and

``` ruby
describe "Validations" do
  subject { Factory.build(:product_tag) }

  must { have_valid(:x).when(1) }
end
```

But both yields error:

``` bash
NoMethodError: undefined method `have_valid' for #<#<Class:0x007fe14bf5ad00>:0x007fe1498f5638>
```

Tried it successfully with Minitest lately?

**Comment by bcardarella** [comment]
I'm guessing you're running into the 1.1 Minitest update issue. This was resolved in: https://github.com/bcardarella/valid_attribute/commit/cf96d8b1544ed068a97d694c3124ac86ea37f398

I have not released an updated version of the gem yet.

Please try pulling from master and if this issue continues I'll reopen.

**Comment by grimen** [comment]
OK I see, thanks for the hint!
