### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by bryanrite** [bcardarella/valid_attribute#18]
I'm not sure if this is a bug, but I have the following issue:

I have a very basic setup:

``` ruby
class Book < ActiveRecord::Base
  belongs_to :customer
  validates :customer_id, presence: true
end
```

And in my RSpec file:

``` ruby
subject { Book.new, :customer_id => 2 }

it "works" do
  subject.customer_id = nil
  subject.should_not have_valid(:customer_id)
end
```

But the following doesn't work:

``` ruby
it { should_not have_valid(:customer_id).when(nil) }
```

I get the error: 

``` ruby
expected Book#customer_id to reject the value: nil
```

As I understand it, they should be the same?  Am I missing something?

Thanks in advance!

**Comment by bcardarella** [comment]
Is this the exact model you have? I just tried to recreate this issue and (I hate when people say this) it works for me. Clearly, it's not working for you. Can you provide more information, or even better, an example app demonstrating the problem?

**Comment by bryanrite** [comment]
Hi Brian, what I provided here does work, but the same code within the project does not, so there is a conflict with the project somewhere, on first glance it might be another testing gem.  I'm going to try and isolate what is causing the issue and I will let you know or submit a pull request.

**Comment by bcardarella** [comment]
Yes, please let me know if you discover a conflict. Thank-you

**Comment by bcardarella** [comment]
In the mean time I'm going to close this issue. Please open another if you discover the source of the conflict.
