### ISSUE TITLE
README incorrect

### ISSUE THREAD

**Issue by noctivityinc** [bcardarella/valid_attribute#24]
I believe the README is incorrect for requiring valid_attribute for unit_tests.  I believe the correct require statement is simply 

require 'valid_attribute/test_unit'

**Comment by bcardarella** [comment]
That should not be the case as this line will detect for `Test::Unit` and load the proper file:

https://github.com/bcardarella/valid_attribute/blob/master/lib/valid_attribute.rb#L15

Are you sure `Test::Unit` is loaded before `ValidAttribute`?

**Comment by bcardarella** [comment]
@noctivityinc can I get an update on this?

**Comment by noctivityinc** [comment]
Sorry. I'm away now but will update you tomorrow. 

J

**Comment by noctivityinc** [comment]
I now have it loaded into a Spork block as such as it works fine so I'll close this.  Thanks.

Spork.prefork do
  # Loading more in this block will cause your tests to run faster. However,
  # if you change any configuration or code from libraries loaded here, you'll
  # need to restart spork for it take effect.

  ENV["RAILS_ENV"] = "test"
  require File.expand_path('../../config/environment', **FILE**)
  require Rails.root.join("db/seeds")
  require 'rails/test_help'
  require "paperclip/matchers"
  # require 'valid_attribute/test_unit'
  require 'valid_attribute'
