### ISSUE TITLE
Any plan to compatible with rspec 3.0.0 ?

### ISSUE THREAD

**Issue by zhu1230** [bcardarella/valid_attribute#32]
now we use the should legacy matcher, which is deprecated in rspec 3.0.0

**Comment by bcardarella** [comment]
I'd accept a PR as we aren't using rspec anymore.

**Comment by zhu1230** [comment]
Cool

**Comment by m5rk** [comment]
#34 solves this (at least it solves the only issue I've run into so far).

**Comment by bcardarella** [comment]
I just released 2.0.0 that includes the changes from #34
